<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: tuvan
 * Date: Sat, 15 Jun 2019 07:47:44 -0500
 */

$conf['title'] = 'Tu Van\'s Wiki';
$conf['template'] = 'monobook';
$conf['license'] = 'cc-by-sa';
$conf['typography'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['plugin']['mdpage']['debug'] = 1;
$conf['plugin']['mdpage']['flavor'] = 'markdown-extra';
$conf['tpl']['monobook']['monobook_sitenotice'] = '0';

// end auto-generated content
